/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualanbukuAW;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author Labkom
 */
public class Buku extends javax.swing.JFrame {
    Connection konek = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private DefaultTableModel m;
    public int session;
    

    /**
     * Creates new form Buku
     */
    public Buku() {
        initComponents();
        
        konek = koneksi.konek("root","root");
        
        m = new DefaultTableModel();
        jTable2.setModel(m);
        m.addColumn("Id");
        m.addColumn("ISBN");
        m.addColumn("Judul Buku");
        m.addColumn("Kategori");
        m.addColumn("Harga");
        ambilData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        ISBN = new javax.swing.JTextField();
        JudulBuku = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        Kategori = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        fieldCari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        UBAH = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        resetCari = new javax.swing.JButton();
        sortir = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM BUKU");

        jLabel2.setText("Id Buku");

        jLabel3.setText("ISBN");

        jLabel4.setText("Judul ");

        jLabel5.setText("Kategori");

        jLabel6.setText("Harga");

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });

        ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNActionPerformed(evt);
            }
        });

        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });
        Harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HargaKeyTyped(evt);
            }
        });

        Kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilihan", "Sastra", "Teknologi", "Sains", "Wirausaha" }));

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseKlikTabel(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setText("Cari data");

        fieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCariActionPerformed(evt);
            }
        });

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        UBAH.setText("UPDATE");
        UBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UBAHActionPerformed(evt);
            }
        });

        HAPUS.setText("DELETE");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        resetCari.setText("Reset Pencarian");
        resetCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCariActionPerformed(evt);
            }
        });

        sortir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Urutkan berdasarkan...", "Id", "JudulBuku", "Kategori", "Harga", " " }));
        sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Harga, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(Kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JudulBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(UBAH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCari))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sortir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(resetCari, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(UBAH)
                    .addComponent(HAPUS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari)
                    .addComponent(resetCari)
                    .addComponent(sortir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reset();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariActionPerformed

    private void mouseKlikTabel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseKlikTabel
        // TODO add your handling code here:
        int lokasi = jTable2.getSelectedRow();
        
        String ID = jTable2.getValueAt(lokasi, 0).toString();
        String isbn = jTable2.getValueAt(lokasi, 1).toString();
        String JUDULBUKU = jTable2.getValueAt(lokasi, 2).toString();
        String KATEGORI = jTable2.getValueAt(lokasi, 3).toString();
        String HARGA = jTable2.getValueAt(lokasi, 4).toString();
        
        id.setText(ID);
        ISBN.setText(isbn);
        JudulBuku.setText(JUDULBUKU);
        Kategori.setSelectedItem(KATEGORI);
        Harga.setText(HARGA);
        id.setEditable(false);
        
        
    }//GEN-LAST:event_mouseKlikTabel

    private void UBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UBAHActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_UBAHActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_HAPUSActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        golek();
        
    }//GEN-LAST:event_cariActionPerformed

    private void resetCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCariActionPerformed
        // TODO add your handling code here:
        resetGolek();
    }//GEN-LAST:event_resetCariActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaActionPerformed

    private void HargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
    }//GEN-LAST:event_HargaKeyTyped

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
    }//GEN-LAST:event_idKeyTyped

    private void sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortirActionPerformed
        // TODO add your handling code here:
        if(sortir.getSelectedIndex() == 0){
            ambilData();
        }else{
        ambilDataSortir();
        }
    }//GEN-LAST:event_sortirActionPerformed
    private void reset(){
        id.setText("");
        ISBN.setText("");
        JudulBuku.setText("");
        Kategori.setSelectedIndex(0);
        Harga.setText("");
        id.setEditable(true);
    }
    
    private void cobaSession(){
        if(session == 0){
            HAPUS.setEnabled(false);
            UBAH.setEnabled(false);
        }else if(session == 1){
            
        }
    }
    
    public void filterhuruf(KeyEvent tekanKeyboard){
        if(Character.isAlphabetic(tekanKeyboard.getKeyChar())){
            tekanKeyboard.consume();
            }
    }
    
    private void resetGolek(){
        fieldCari.setText("");
    }
    
    private void update(){
        if(id.getText().equals("")||ISBN.getText().equals("")||JudulBuku.getText().equals("")||Harga.getText().equals("")||Kategori.getSelectedItem().equals("")){
         JOptionPane.showMessageDialog(this, "Pilih data dari tabel dahulu!");
        }else{
            
            String perintah = "UPDATE buku set ISBN ='"+ISBN.getText().toString()+"',JudulBuku ='"+JudulBuku.getText().toString()+"',Harga ='"+Harga.getText().toString()+"',Kategori ='"+Kategori.getSelectedItem()+"' WHERE id ='"+id.getText().toString()+"'";
            try{
               PreparedStatement pst = konek.prepareStatement(perintah);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(this, "Data berhasil dirubah");
               reset();
               ambilData();
            }catch(SQLException k){
                JOptionPane.showMessageDialog(this, k);
            }
        }
    }
    
    private void hapus(){
        if(id.getText().equals("")||ISBN.getText().equals("")||JudulBuku.getText().equals("")||Harga.getText().equals("")||Kategori.getSelectedItem().equals("")){
         JOptionPane.showMessageDialog(this,"Pilih data dari tabel dahulu!");   
        }else{
            String perintah = "DELETE FROM buku WHERE id ='"+id.getText().toString()+"'";
            try{
                int p = 
               JOptionPane.showConfirmDialog(this, "Konfirmasi","Peringatan",JOptionPane.YES_NO_OPTION);
                if(p == JOptionPane.YES_OPTION){
                    
                
               PreparedStatement pst = konek.prepareStatement(perintah);
               pst.executeUpdate();
               
               JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
               reset();
               ambilData();
               }
            }catch(SQLException k){
                JOptionPane.showMessageDialog(this, k);
            }
            
        }
    }
    
    public void golek(){
        //Kosongkan Tabel
        m.getDataVector().removeAllElements();
        m.fireTableDataChanged();
     try{
           
            String perintah = "SELECT*FROM buku WHERE id like '%"+fieldCari.getText().toString()+"%'"+"OR ISBN like '%"+fieldCari.getText().toString()+"%'"+"OR JudulBuku like '%"+fieldCari.getText().toString()+"%'";
            pst = konek.prepareStatement(perintah);
            rs   = pst.executeQuery(perintah);
            if(rs.getFetchSize() <= 0){
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
                ambilData();
            }
           
           while(rs.next()){
                     m.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    
                });
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
      }
     
}
    
    public void ambilData(){
        //Kosongkan Tabel
        m.getDataVector().removeAllElements();
        m.fireTableDataChanged();
     try{
           
            String perintah = "SELECT*FROM buku";
            pst = konek.prepareStatement(perintah);
            rs   = pst.executeQuery(perintah);
           
           while(rs.next()){
                     m.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    
                });
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
     
}
    public void ambilDataSortir( ){
        //Kosongkan Tabel
        m.getDataVector().removeAllElements();
        m.fireTableDataChanged();
     try{
           
            String perintah = "SELECT*FROM buku ORDER BY "+sortir.getSelectedItem().toString().trim()+" ASC";
            pst = konek.prepareStatement(perintah);
            rs   = pst.executeQuery(perintah);
           
           while(rs.next()){
                     m.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    
                });
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
     
}
    
    private void simpan(){
        if(id.getText().equals("")||ISBN.getText().equals("")||JudulBuku.getText().equals("")||Harga.getText().equals("")||Kategori.getSelectedItem().equals("")){
         JOptionPane.showMessageDialog(this,"Data Harus Di Isi");   
        }else{
            String perintah = "INSERT INTO buku (id,ISBN,JudulBuku,Kategori,Harga) VALUES ('"+id.getText().toString()+"','"+ISBN.getText().toString()+"','"+JudulBuku.getText().toString()+"','"+Kategori.getSelectedItem()+"','Rp "+Harga.getText().toString()+"')";
            try{
               PreparedStatement pst = konek.prepareStatement(perintah);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(this, "Data berhasil masuk");
               reset();
               ambilData();
            }catch(SQLException k){
                JOptionPane.showMessageDialog(this, k);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HAPUS;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField ISBN;
    private javax.swing.JTextField JudulBuku;
    private javax.swing.JComboBox<String> Kategori;
    private javax.swing.JButton UBAH;
    private javax.swing.JButton cari;
    private javax.swing.JTextField fieldCari;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton resetCari;
    private javax.swing.JComboBox sortir;
    // End of variables declaration//GEN-END:variables
}
